import cv2

TARGET_IMAGE = cv2.imread("sublime.jpg")

NUMBER_OF_ITERATIONS = 5000
POPULATION_SIZE = 10

NUMBER_OF_CIRCLES = 1000
CIRCLE_RADIUS = 5

MAX_MUT_RATIO = 0.3
COLOR_MUT_PB = 0.8
CENTER_MUT_PB = 0.6
